.TH "src/include/Config.h" 3 "Thu Jun 8 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Config.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Consts\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTACK_INIT_SIZE\fP   0x00"
.br
.ti -1c
.RI "#define \fBSTRING_INIT_SIZE\fP   0x00"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBSIZE_OF_INT\fP = sizeof(int)"
.br
.ti -1c
.RI "const int \fBSIZE_OF_LONG\fP = sizeof(long)"
.br
.ti -1c
.RI "const int \fBSIZE_OF_CHAR\fP = sizeof(char)"
.br
.ti -1c
.RI "const int \fBSIZE_OF_DOUBLE\fP = sizeof(double)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STACK_INIT_SIZE   0x00"

.SS "#define STRING_INIT_SIZE   0x00"

.SH "Variable Documentation"
.PP 
.SS "const int SIZE_OF_CHAR = sizeof(char)"

.SS "const int SIZE_OF_DOUBLE = sizeof(double)"

.SS "const int SIZE_OF_INT = sizeof(int)"
Copyright (c) 2017 Matheus Silva 
.SS "const int SIZE_OF_LONG = sizeof(long)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
