.TH "src/Consts.h" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Consts.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   ((void *) 0)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBbool\fP { \fBtrue\fP = 1, \fBfalse\fP = 0 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NULL   ((void *) 0)"
Copyright (c) 2017 Matheus Silva 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBbool\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fItrue \fP\fP
.TP
\fB\fIfalse \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
