.TH "deprecated" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecatedDeprecated List 
 \- 
.IP "\fBGlobal \fBstack::getsizeof_stack\fP (Stack *stack)\fP" 1c
Will be removed on next major, use:  
.IP "\fBGlobal \fBstack::stack_check\fP (Stack *stack)\fP" 1c
.PP

