.TH "src/libDefines.h" 3 "Thu Jun 8 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libDefines.h
.SH SYNOPSIS
.br
.PP
\fC#include 'include\\Stack\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStack\fP \fBto_rpn\fP (char **raw)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBStack\fP to_rpn (char ** raw)"
Copyright (c) 2017 Matheus Silva 
.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
