.TH "src/libforge.h" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libforge.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Stack\&.h'\fP
.br
\fC#include 'to_rpn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIB_VER\fP   20170609"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStack\fP \fBto_rpn\fP (char **raw)"
.br
.ti -1c
.RI "void \fBstack_init\fP (\fBStack\fP *\fBstack\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "void \fBstack_free\fP (\fBStack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "void \fBstack_resize\fP (\fBStack\fP *\fBstack\fP, int qty)"
.br
.ti -1c
.RI "void \fBstack_push\fP (\fBStack\fP *\fBstack\fP, int \fBdata\fP)"
.br
.ti -1c
.RI "int \fBstack_pop\fP (\fBStack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "int \fBstack_check\fP (\fBStack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "int \fBgetsizeof_stack\fP (\fBStack\fP *\fBstack\fP)"
.br
.ti -1c
.RI "void \fBstack_merge\fP (\fBStack\fP *stack1, \fBStack\fP *stack2)"
.br
.ti -1c
.RI "int \fBstack_traverse\fP (\fBStack\fP *\fBstack\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2017 Matheus Xavier Silva 
.RE
.PP
\fBAuthor:\fP
.RS 4
Matheus Xavier Silva 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define LIB_VER   20170609"

.SH "Function Documentation"
.PP 
.SS "int getsizeof_stack (\fBStack\fP * stack)"

.SS "int stack_check (\fBStack\fP * stack)"

.SS "void stack_free (\fBStack\fP * stack)"

.SS "void stack_init (\fBStack\fP * stack, int size)"

.SS "void stack_merge (\fBStack\fP * stack1, \fBStack\fP * stack2)"

.SS "int stack_pop (\fBStack\fP * stack)"

.SS "void stack_push (\fBStack\fP * stack, int data)"

.SS "void stack_resize (\fBStack\fP * stack, int qty)"

.SS "int stack_traverse (\fBStack\fP * stack)"

.SS "\fBStack\fP to_rpn (char ** raw)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
