.TH "src/Stack.h" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Stack.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'Config\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBstack\fP"
.br
.RI "Standard FILO stack with a traverse function to get any specific index\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstack_traverse\fP (\fBStack\fP *\fBstack\fP, int index)"
.br
.RI "Traverse the stack to the desired index\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2017 Matheus Xavier Silva 
.RE
.PP
\fBAuthor:\fP
.RS 4
Matheus Xavier Silva 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int stack_traverse (\fBStack\fP * stack, int index)"

.PP
Traverse the stack to the desired index\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstack\fP 
.br
\fIindex\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
