.TH "Stack" 3 "Thu Jun 8 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stack
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcapacity\fP"
.br
.ti -1c
.RI "int * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (c) 2017 Matheus Silva \fBStack\fP data-type with the two stack operations push and pop, plus a stack_get_arbitrary operation to get the value at an arbitrary position on the stack 
.SH "Field Documentation"
.PP 
.SS "int capacity"

.SS "int* data"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
