.TH "src/String.h" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/String.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'Config\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBString\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstring_init\fP (\fBString\fP *str, \fBbool\fP appendnull)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void string_init (\fBString\fP * str, \fBbool\fP appendnull)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
