.TH "String" 3 "Thu Jun 8 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <String\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcapacity\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (c) 2017 Matheus Silva 
.SH "Field Documentation"
.PP 
.SS "int capacity"

.SS "char* data"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
