.TH "src/Test.c" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Test.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libDefines\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
