.TH "src/Vector.h" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Vector.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'Config\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvector\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBvector\fP \fBVector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBvector_init\fP (\fBVector\fP *\fBvector\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "void \fBvector_free\fP (\fBVector\fP *\fBvector\fP)"
.br
.ti -1c
.RI "void \fBvector_resize\fP (\fBVector\fP *\fBvector\fP, int qty)"
.br
.ti -1c
.RI "void \fBvector_push\fP (\fBVector\fP *\fBvector\fP, int \fBdata\fP)"
.br
.ti -1c
.RI "int \fBvector_pop\fP (\fBVector\fP *\fBvector\fP)"
.br
.ti -1c
.RI "int \fBvector_check\fP (\fBVector\fP *\fBvector\fP)"
.br
.ti -1c
.RI "int \fBgetsizeof_vector\fP (\fBVector\fP *\fBvector\fP)"
.br
.ti -1c
.RI "void \fBvector_merge\fP (\fBVector\fP *vector1, \fBVector\fP *vector2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2017 Matheus Xavier Silva 
.RE
.PP
\fBAuthor:\fP
.RS 4
Matheus Xavier Silva 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBvector\fP \fBVector\fP"

.SH "Function Documentation"
.PP 
.SS "int getsizeof_vector (\fBVector\fP * vector)"
Gets the size of the vector 
.SS "int vector_check (\fBVector\fP * vector)"
Gets the topmost item on the vector 
.SS "void vector_free (\fBVector\fP * vector)"
Free the memory allocated to the vector passed as argument 
.SS "void vector_init (\fBVector\fP * vector, int size)"
Initialise the vector 
.SS "void vector_merge (\fBVector\fP * vector1, \fBVector\fP * vector2)"
Merges vector1 into vector2 Returns: nothing the resulting vector in vector2 
.SS "int vector_pop (\fBVector\fP * vector)"
Pop from the vector 
.SS "void vector_push (\fBVector\fP * vector, int data)"
Push to the vector 
.SS "void vector_resize (\fBVector\fP * vector, int qty)"
Increase capacity by a given number defaults to 1 
.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
