.TH "vector" 3 "Fri Jun 9 2017" "Version 0.0.1" "ForgeLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vector\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBpopc\fP"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcapacity\fP"
.br
.ti -1c
.RI "int * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector data-type 
.SH "Field Documentation"
.PP 
.SS "int capacity"

.SS "int* data"

.SS "\fBbool\fP popc"

.SS "int size"

.SS "int top"


.SH "Author"
.PP 
Generated automatically by Doxygen for ForgeLib from the source code\&.
